# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VCX-5azW6UkNPC0n0b0eC2Mu2BtHzm2Z

## Displaying my name adress and phone number
"""

#2.displaying about me
name= ("Fathima Zulfa")
adress= ("Thalangara, Theruvath, Kasaragod, Kerala")
number=("9961822432")
print(name);print(adress);print(number)

"""# Evaluating the given program"""

#3.checking question
print("your name is",j)
name="Fathima Zulfa"
print("your name is",j)
#the program throws syntax error on the first line

"""# Area of a rectangle"""

#4.area of rectangle
def computing_area():
  width=int(input("Enter the width:"))
  height=int(input("Enter the height:"))
  area= width*height
  print("the area is:",area,"square unit.")

computing_area()

computing_area()

computing_area()

"""# Area of a triangle"""

#5.area of a trianle
base=int(input("Enter the base:"))
height= int(input("Enter the height:"))
area= 0.5*base*height
print("The area is:",area,"sq unit")

"""# Area of a circle"""

#7.area of a circle
radius=int(input("Enter the radius:"))
area= 3.14*radius**2
print("the area of the circle is:",area,"sq unit")

"""# Persons name and age"""

#7.printing name and age
name=input("enter your name:")
name=name.upper()
age =input("enter your age:")
int(age)
print("your name is",name,"and age is",age,".")

"""# Adding 1 to a number"""

#8.adding 1 if entered a number
text=input("enter anything you wish:")
try:
  text=int(text)
  i=text+1
  print("we get",i,"on adding 1 to",text)
except:
  print("you have entered:",text)

"""# Priting my name"""

#9.print what i type
text=input("enter your first name:")
if text==("sarith"):
 print("Hello, Sarith Divaker!")
else:
  print("not users first name")